language: python
python:
  - "3.7"

env:
  - PYTHONPATH=yugiohbot

services:
  - docker

install:
  - mkdir -p package/nltk_data/
  - pip install -r requirements.txt
  - pip install -r requirements.txt -t package
  - python -m nltk.downloader punkt averaged_perceptron_tagger wordnet
  - cp -a ~/nltk_data/. package/nltk_data/
  - cp -a yugiohbot/. package/
  - chmod +x ./integration.sh
  - docker pull lambci/lambda:python3.7

script:
  - pytest --cov=./ --ignore=package
  - ./integration.sh

after_success:
  - codecov
